#ifndef _EDGE_DEFINES_H_
#define  _EDGE_DEFINES_H_

#define OCALL_PRINT_BUFFER 1
#define OCALL_PRINT_VALUE 2
#define OCALL_SEND_REPORT 3
#define OCALL_WAIT_FOR_MESSAGE 4
#define OCALL_SEND_REPLY 5
#define OCALL_WAIT_FOR_CLIENT_PUBKEY 6
#define OCALL_INIT_CONN 7
#define OCALL_SEND_FD 8
#define OCALL_RECV_FD 9
#define OCALL_TERM_FD 10
#define OCALL_INIT_SERV_CONN 11
#define OCALL_WAIT_FOR_CONN 12
#define OCALL_GET_USER_RECORD 13
#define OCALL_SET_USER_RECORD 14
#define OCALL_GET_RULE_RECORD 15
#define OCALL_SET_RULE_RECORD 16

#endif /* _EDGE_DEFINES_H_ */
