add_wolfssl(${host_bin}-wolfssl
   "96822135add15b1478b76354bb3d05ce56b83a3f"
   "musl"
   "-DWOLFSSL_SMALL_STACK -DWOLFSSL_CUSTOM_OID -DHAVE_OID_ENCODING -DHAVE_OID_DECODING -DOPENSSL_EXTRA -DWOLFSSL_VERIFY_CB_ALL_CERTS -DWOLFSSL_ALWAYS_VERIFY_CB -DWOLFSSL_NO_ASN_STRICT"
)

